{
	"version": 1628257397,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/leftbutton.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/papanscore-sheet0.png",
		"images/replay-sheet0.png",
		"images/stop-sheet0.png",
		"images/star-sheet0.png",
		"images/ski_jatuh-sheet0.png",
		"images/character-sheet0.png",
		"images/character-sheet1.png",
		"images/character-sheet2.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/heart-sheet0.png",
		"images/heart-sheet1.png",
		"images/tiledbackground.png",
		"images/efekhit-sheet0.png",
		"images/dini_fransiska-sheet0.png",
		"images/startbutton-sheet0.png",
		"images/laneguide.png",
		"media/mattoglseby - 3.ogg",
		"media/mattoglseby - 7.ogg",
		"media/mattoglseby - 4.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}