{
	"version": 1628761101,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/leftbutton.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/papanscore-sheet0.png",
		"images/replay-sheet0.png",
		"images/stop-sheet0.png",
		"images/star-sheet0.png",
		"images/ski_jatuh-sheet0.png",
		"images/character-sheet0.png",
		"images/character-sheet1.png",
		"images/character-sheet2.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/heart-sheet0.png",
		"images/heart-sheet1.png",
		"images/tiledbackground.png",
		"images/efekhit-sheet0.png",
		"images/home_menu-sheet0.png",
		"images/stagelock-sheet0.png",
		"images/stageopen-sheet0.png",
		"images/stageselectbackground-sheet0.png",
		"media/ok - 1.ogg",
		"media/ok - 2.ogg",
		"media/thud 1.ogg",
		"media/mattoglseby - 3.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}